---
title: "about"
author: "Mengyuan Li"
date: "10/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

MENGYUAN LI

50 Haven Avenue #B-155, New York, 10032| Cell 848-391-8351 |    

ml4418@cumc.columbia.edu

SUMMARY

Master student at Columbia University-Mailman School of Public Health majoring in Biostatistics who has creative thinking ability, friendly and reliable personalities, excellent communication skills, and strong math knowledge.

EDUCATION

Columbia University, Mailman School of public Health, New York

•	Graduate Year: May 2021

•	Major: MS in Biostatistics

•	Track: Method and Theory

Rutgers University, New Brunswick, NJ

•	Graduated Year: August 2019

•	Major: Mathematics 

•	Minor: Philosophy

•	GPA:3.33/4.0

•	Achievement: Deans List

LANGUAGES

Fluent in English and Chinese

SKILLS RELATED MATH

•	MATLAB

•	Maple

•	Logic 

•	Linear Algebra

•	Calculus I, II, III, IV, V

RELATED EXPERIENCE

January 2018 - Present

San Cai Art, Edison, NJ

•	Teaching young children to create colored pencil artworks

•	Communicating with parents about their children’s progress 

March 2016 - May 2017

Rutgers Chinese Students and Scholars Association (RCSSA)

•	Helped Rutgers Chinese Students and Scholars Association (RCSSA) find investors and funds from nearby companies and agencies.

•	Organized activities selling Student VIP cards
Winter 2015 – January 2016
Subdistrict Office of Kundulun Distinct, Baotou, China

•	Helped Subdistrict Office researchers collect and select information about residents’ health conditions and immunization history in a certain community

•	Negotiated with residents in order to get their personal health information
